version: '3'

services:
  db:
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: postgres
  web:
    build: .
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - SECRET_KEY=e%v+a%z^-hsti3^*9y&_yipn)9sb8wm&idz&x3ub*skso&%3jq
      - DB_USER=postgres
      - DB_NAME=postgres
      - DB_PASSWORD=postgres
      - DB_HOST=db
      - DB_PORT=5432
